#!/bin/bash

# get current local peer name
LOCAL=`cat .author-cb/git-cb`
EMAIL="$LOCAL@unibas.ch"

# Read pub-key
sha_pubkey=`cat .author-cb/key.pub | sha1sum | awk '{print $1}'`

echo "I am post recieve"

read oldrev newrev remote_refname

# echo $oldrev $newrev $remote_refname  

if [[ $remote_refname == *"/groupConv/"* ]]; then

    # echo "Group conversation received!!"
    sub_g_id=`echo $remote_refname | awk -F"/" '{print $4}'`
    local_refname="refs/heads/groupConv/$sub_g_id/$sha_pubkey"
    local_refname_present=`git show-ref $local_refname`

    curr_group_state=`git show -s $newrev --format="%T"`
    g_id=`git cat-file -p $curr_group_state | grep tree | awk '{print $4}'` 
    group_name=`git cat-file -p $curr_group_state:group_name`
    # echo "Current group state is $curr_group_state"
    # echo "Group id is : $g_id"
    # echo "Group name is '$group_name'"
    if [[ -z $local_refname_present ]]; then 
        echo "Pushed first time. Creating direct merge commit."
        source ./hooks/commit_helper.sh
        CSV_INFO="$g_id,$group_name,"",$curr_group_state,remote"
        echo $CSV_INFO >> .author-cb/db.csv
        exit 0
    fi
    echo "Was already pushed... Check the group state hash different of not!"
    local_commit=`echo $local_refname_present | awk '{print $1}'`
    local_group_state=`git show -s $local_commit --format="%T"`
    # echo $local_group_state
    
    if [[ "$local_group_state" != "$curr_group_state" ]]; then
        echo "Both not equal"
        echo "Perform merge operation"
        source ./hooks/merge_helper.sh
        # echo "New group state is $new_group_state_tree"
        if [[ "$local_group_state" == "$new_group_state_tree" ]]; then 
	   echo "Nothing to do!!"
           exit 0
	fi
	curr_group_state=$new_group_state_tree
        echo "Now curr group state is $curr_group_state"
        source ./hooks/commit_helper.sh
        group_info_in_local=`cat .author-cb/db.csv | grep -nE "$g_id,"`
        row_num=`echo $group_info_in_local | awk -F':' '{print $1}'`
        curr_group_name=`echo $group_info_in_local | awk -F, '{print $2}'`
        old_group_name=`echo $group_info_in_local | awk -F, '{print $3}'`
        created_at=`echo $group_info_in_local | awk -F, '{print $5}'`

        if [[ "$group_name" != "$curr_group_name" ]]; then 
            old_group_name=$curr_group_name
            curr_group_name=$group_name
        fi
        CSV_INFO="$g_id,$curr_group_name,$old_group_name,$curr_group_state,$created_at"
        echo "$CSV_INFO ---- in rowNum: $row_num"
        sed -i "${row_num}s/.*/$CSV_INFO/" .author-cb/db.csv
    fi
fi
